package com.sz.expert.disease

import com.sz.expert.disease.Disease

rule "Tuberculosis"
	when 
		disease: Disease(
		    highFever
		    && violetLimbs
		    && cough
		    && bronchospasm
            && xray == "dark"
            && whistle
            && highWhiteBloodCells
		);
	then
		disease.setTuberculosis(true);
	end

rule "Pneumothorax"
	when
		disease: Disease(
		    neckPain
		    && cough
		    && bronchospasm
            && xray == "dark"
            && whistle
		);
	then
		disease.setPneumothorax(true);
	end

rule "Pneumonia"
	when
		disease: Disease(
		    highFever
		    && neckPain
		    && xray == "white"
            && highWhiteBloodCells
		);
	then
		disease.setPneumonia(true);
	end

rule "Flu"
	when
		disease: Disease(
		    highFever
		    && cough
            && xray == "clear"
            && highOxygen
		);
	then
		disease.setFlu(true);
	end
